name: Run Tests
on:
  push:
  pull_request:

jobs:
  test-frontend:
    name: Frontend Tests
    runs-on: ubuntu-latestn
    defaults:
        run:
          working-directory: ./apps/frontend

    steps:
          - name: Checkout repository
            uses: actions/checkout@v4

          - name: Setup Node.js
            uses: actions/setup-node@v4
            with:
              node-version: 'v24.14.0'

          - name: Clean Install
            run: npm ci
          
          - name: Run tests
            run: npm test
          
  test-backend:
    name: Backend Tests
    runs-on: ubuntu-latestn
    defaults:
        run:
          working-directory: ./apps/backend

    steps:
          - name: Checkout repository
            uses: actions/checkout@v4

          - name: Setup Node.js
            uses: actions/setup-node@v4
            with:
              node-version: 'v24.14.0'

          - name: Clean Install
            run: npm ci
          
          - name: Run tests
            run: npm test

        
